apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitsrv
  name: gitsrv
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: ssh
  selector:
    name: gitsrv
  type: ClusterIP
