apiVersion: v1
kind: Service
metadata:
  labels:
    name: signalbox
  name: signalbox
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: signalbox
  type: ClusterIP
