# !/bin/bash

ssh-keygen -t rsa -N "" -f "id_rsa"
chmod 700 id_rsa

# Initial key needed for Flux bootstrap
kubectl create secret generic flux-bootstrap \
  --from-file="id_rsa.pub"

# Populate this secret with the SSH generated by Flux bootstrap
cp id_rsa.pub flux_id_rsa.pub
kubectl create secret generic flux-git-deploy \
  --from-file="flux_id_rsa.pub"

kubectl apply -f gitsrv/
kubectl rollout status deployment/gitsrv

POD_GITSRV=$(kubectl get pod -l name=gitsrv -o jsonpath="{.items[0].metadata.name}")
sudo kubectl port-forward $POD_GITSRV 22:22 &

# Use bootstrap SSH key to bootstrap Flux resources into the Git server
flux bootstrap git --url=ssh://git@localhost/home/git/cluster --branch=master \
  --path=clusters/my-cluster --private-key-file=id_rsa
