apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mypod
  name: mypod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mypod
  template:
    metadata:
      labels:
        name: mypod
    spec:
      containers:
        - name: git
          image: alpine/git
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /git-server/keys
              name: ssh-key
          command:
            - sleep
            - "1000"
      volumes:
        - name: ssh-key
          secret:
            secretName: ssh-key
