apiVersion: v1
kind: Service
metadata:
  labels:
    name: echo
  name: echo
spec:
  ports:
    - name: ssh
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: echo
  type: ClusterIP
