apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: webhook
  namespace: flux-system
spec:
  type: generic
  address: http://echo.default.svc.cluster.local
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: kustomizations
  namespace: flux-system
spec:
  providerRef: 
    name: webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: 'podinfo'
    - kind: Kustomization
      name: 'podinfo'
