apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: echo-server
  namespace: flux-system
spec:
  type: generic
  address: http://echo.default.svc.cluster.local
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: echo-server
  namespace: flux-system
spec:
  providerRef: 
    name: echo-server
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: signalbox
  namespace: flux-system
spec:
  type: generic
  address: http://signalbox.default.svc.cluster.local/receive
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: signalbox
  namespace: flux-system
spec:
  providerRef: 
    name: signalbox
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
